# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kha Nguyen
locale: en-US
email: nguyentrongkha92@gmail.com
logo: /images/avatar.jpeg
description: A Man who like to breaking things
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ngtrongkha.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: __ngtrongkha
github_username:  lotusirous

# Build settings
markdown: kramdown
mathjax: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
  - name: "Playfair Display"
    weights: "400,400i,700,700i"


paginate: 10  # amount of posts to show per page
paginate_path: /page:num/
date_format: "%Y-%m-%d"
read_time: true
words_per_minute: 200
mathjax: true

permalink: /:categories/:title/
search_full_content: false # optimize performance

google_analytics: "UA-73002749-1"
author:
  name: Kha Nguyen
  twitter: __ngtrongkha
  picture: /images/avatar.jpeg

disqus:
  shortname: trong_kha
twitter:
  username: __ngtrongkha

footer_links:
  - title: Twitter
    url: https://twitter.com/__ngtrongkha
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/lotusirous
    icon: fab fa-github-square
  
  - title: Medium
    url: https://github.com/lotusirous
    icon: fab fa-medium
